#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




python manage.py migrate
echo "collectstatic"
python /app/manage.py collectstatic --noinput
echo "gunicorn"
/usr/local/bin/gunicorn cid.wsgi:application --bind 0.0.0.0:8000 --chdir=/app
