# Generated by Django 3.2.5 on 2021-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('cpu', models.CharField(max_length=120)),
                ('ram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
            ],
        ),
    ]
