# Generated by Django 3.2.5 on 2021-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='os',
            name='os_id',
            field=models.CharField(max_length=120),
        ),
    ]
