# Generated by Django 3.2.5 on 2021-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210727_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='os',
            name='os_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
