# Generated by Django 3.2.5 on 2021-07-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210727_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.os'),
            preserve_default=False,
        ),
    ]
