# Generated by Django 3.2.5 on 2021-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_model_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='os',
            unique_together={('name', 'type')},
        ),
    ]
