# Generated by Django 3.2.5 on 2021-08-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_os_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='os',
            old_name='os_id',
            new_name='os',
        ),
    ]
