# Generated by Django 3.2.5 on 2021-08-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210831_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='user',
        ),
    ]
