# Generated by Django 3.2.5 on 2021-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_employee_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('employee', models.ManyToManyField(to='inventory.Employee')),
            ],
        ),
    ]
