# Generated by Django 3.2.5 on 2021-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Employee'),
        ),
    ]
