# Generated by Django 3.2.5 on 2021-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_software_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='software',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Software'),
        ),
    ]
