# Generated by Django 3.2.5 on 2021-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210901_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='editor',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(default='1.0.0', max_length=255),
            preserve_default=False,
        ),
    ]
