# Generated by Django 3.2.5 on 2021-09-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210901_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='user',
            new_name='employee',
        ),
    ]
