# Generated by Django 3.2.5 on 2021-09-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_machine_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='assigned',
        ),
    ]
